---
# clear cache 2019-08-07
image: Visual Studio 2017

deploy: off

clone_depth: 5

init:
  # Remove any ENV settings related to OpenSSL-Win
  - ps: |
      Remove-Item env:SSL_CERT_DIR  -ErrorAction SilentlyContinue
      Remove-Item env:SSL_CERT_FILE -ErrorAction SilentlyContinue
      Remove-Item env:OPENSSL_CONF  -ErrorAction SilentlyContinue

install:
  # Update MSYS2 / MinGW and install OpenSSL
  - ps: |
      git clone -q --depth=5  --no-tags --branch=master https://github.com/oneclick/rubyinstaller2.git    ./rubyinstaller2
      # git clone -q --depth=5  --no-tags --branch=master https://github.com/ConnorAtherton/rb-readline.git ./ruby_readline
      git clone -q --depth=10 --no-tags --branch=master https://github.com/ruby/ruby.git                  ./ruby
      # cd ruby ; git checkout -qf b009de13bf4bb7c96964c404fb56b3503db777fd ; cd ..
      $env:path = "C:\Ruby25-x64\bin;$env:path"
      .\trunk_msys2.ps1

build_script:
  # builds, installs
  - ps: ./1_0_build_install_64.ps1

test_script:
  # tests, generates logs and artifacts
  - ps: ./2_0_test.ps1


cache:
  # 2018-12-27
  - C:\projects\ruby-loco\.downloaded-cache -> appveyor.yml
